project:
  type: website
  output-dir: docs

website:
  title: "Troy Bauce"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Blogs"
        href: https://troybauce.github.io/blogs
      - href: contact.qmd
        text: Contact


format:
  html:
    theme: 
    - solar
    css: styles.css
    



