project:
  type: website
  output-dir: docs

website:
  title: "Troy Bauce"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Blogs"
        menu:
         - text: Research vs. Reality
           href: blog1.qmd
      - href: contact.qmd
        text: Contact


format:
  html:
    theme:
      - vapor
      - brand
    css: styles.css
    



